  rm -r .x*
  rm -r .t*
  rm -r .o*
  rm -r .p*
  rm -r .q*
  rm -r .s*
  rm -r .X*
  rm -r .mplayer/
  rm -r .g*
  rm -r .a*
  rm -r .b*
  rm -r .c*
  rm -r .dbus/
  rm -r .directory 
  rm -r .dmrc 
  rm -r .ICEauthority 
  rm -r .kaboom.log 
  rm -r .kde/
  rm -r .local/
  rm -r .recently-used 
  rm -r .macromedia/
